import comp from "C:/Users/98301/work/yishulun_com_blog/src/.vuepress/.temp/pages/2023/11/12/40.html.vue"
const data = JSON.parse("{\"path\":\"/2023/11/12/40.html\",\"title\":\"警惕潜伏在生活环境中的假酒，谈日常如何选择安全又便宜的粮食酒？\",\"lang\":\"zh-CN\",\"frontmatter\":{\"date\":\"2023-11-12T11:29:00.000Z\",\"gitInclude\":[],\"description\":\"winewine 警惕潜伏在生活环境中的假酒，谈日常如何选择安全又便宜的粮食酒？ 你好，今天聊一下酒。 二三十年前，你在报纸上经常能看到这样的消息，某某地方举办婚宴或寿宴，客人喝了假酒，导致数人不幸身亡、多人双目失明之类的新闻。原因在于宴请所用的酒不是纯粮食酿造的，是工业酒精勾兑的，含有甲醇、吡啶等违害人类健身的物质。最近这方面的新闻少了，但随着直播卖...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://yishulun.com/2023/11/12/40.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"艺述论\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"警惕潜伏在生活环境中的假酒，谈日常如何选择安全又便宜的粮食酒？\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"winewine 警惕潜伏在生活环境中的假酒，谈日常如何选择安全又便宜的粮食酒？ 你好，今天聊一下酒。 二三十年前，你在报纸上经常能看到这样的消息，某某地方举办婚宴或寿宴，客人喝了假酒，导致数人不幸身亡、多人双目失明之类的新闻。原因在于宴请所用的酒不是纯粮食酿造的，是工业酒精勾兑的，含有甲醇、吡啶等违害人类健身的物质。最近这方面的新闻少了，但随着直播卖...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-11-12T11:29:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"警惕潜伏在生活环境中的假酒，谈日常如何选择安全又便宜的粮食酒？\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-11-12T11:29:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"李艺\\\",\\\"url\\\":\\\"https://yishulun.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"酒按工艺划分\",\"slug\":\"酒按工艺划分\",\"link\":\"#酒按工艺划分\",\"children\":[{\"level\":3,\"title\":\"液态法白酒\",\"slug\":\"液态法白酒\",\"link\":\"#液态法白酒\",\"children\":[]},{\"level\":3,\"title\":\"固液法白酒\",\"slug\":\"固液法白酒\",\"link\":\"#固液法白酒\",\"children\":[]},{\"level\":3,\"title\":\"固态法白酒\",\"slug\":\"固态法白酒\",\"link\":\"#固态法白酒\",\"children\":[]}]},{\"level\":2,\"title\":\"粮食洒生产标准\",\"slug\":\"粮食洒生产标准\",\"link\":\"#粮食洒生产标准\",\"children\":[]},{\"level\":2,\"title\":\"20 元以下的口粮酒\",\"slug\":\"_20-元以下的口粮酒\",\"link\":\"#_20-元以下的口粮酒\",\"children\":[]},{\"level\":2,\"title\":\"百元以下优质口粮酒\",\"slug\":\"百元以下优质口粮酒\",\"link\":\"#百元以下优质口粮酒\",\"children\":[]},{\"level\":2,\"title\":\"小酒坊的私房酒值不值得买？\",\"slug\":\"小酒坊的私房酒值不值得买\",\"link\":\"#小酒坊的私房酒值不值得买\",\"children\":[]},{\"level\":2,\"title\":\"回顾\",\"slug\":\"回顾\",\"link\":\"#回顾\",\"children\":[]}],\"readingTime\":{\"minutes\":11.02,\"words\":3305},\"filePathRelative\":\"posts/2023/40.md\",\"localizedDate\":\"2023年11月12日\",\"excerpt\":\"<figure><figcaption>wine</figcaption></figure>\\n<h1>警惕潜伏在生活环境中的假酒，谈日常如何选择安全又便宜的粮食酒？</h1>\\n\\n<p>你好，今天聊一下酒。</p>\\n<p>二三十年前，你在报纸上经常能看到这样的消息，某某地方举办婚宴或寿宴，客人喝了假酒，导致数人不幸身亡、多人双目失明之类的新闻。原因在于宴请所用的酒不是纯粮食酿造的，是工业酒精勾兑的，含有甲醇、吡啶等违害人类健身的物质。最近这方面的新闻少了，但随着直播卖酒的兴起，这类事情又有所抬头，我们必须谨慎对待。</p>\\n<p>酒的文化在中国由来已久，在《水浒传》中，武松景阳岗打虎前喝了 18 碗壮魂酒；在金庸小说《笑傲江湖》中，祖千秋与令狐冲斗酒，从诗、行酒令，到酒杯与酒，每方面都有很多讲究；在《天龙八部》中，乔峰聚贤庄大杀四方前先与昔日老友喝了一碗断交酒。在中国，酒不仅是酒，还附带了其它许多东西。</p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
