import comp from "C:/Users/98301/work/yishulun_com_blog/src/.vuepress/.temp/pages/0000/00/00/privacy.html.vue"
const data = JSON.parse("{\"path\":\"/0000/00/00/privacy.html\",\"title\":\"YishuLun Blog Privacy Policy\",\"lang\":\"zh-CN\",\"frontmatter\":{\"gitInclude\":[],\"description\":\"YishuLun Blog Privacy Policy Welcome to our products. YishuLun Blog (including services provided by the website and other products, hereinafter referred to as \\\"products and serv...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://yishulun.com/0000/00/00/privacy.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"艺述论\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"YishuLun Blog Privacy Policy\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"YishuLun Blog Privacy Policy Welcome to our products. YishuLun Blog (including services provided by the website and other products, hereinafter referred to as \\\"products and serv...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"YishuLun Blog Privacy Policy\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"李艺\\\",\\\"url\\\":\\\"https://yishulun.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"1. How We Collect and Use Your Personal Information\",\"slug\":\"_1-how-we-collect-and-use-your-personal-information\",\"link\":\"#_1-how-we-collect-and-use-your-personal-information\",\"children\":[]},{\"level\":2,\"title\":\"2. How We Store and Protect Your Personal Information\",\"slug\":\"_2-how-we-store-and-protect-your-personal-information\",\"link\":\"#_2-how-we-store-and-protect-your-personal-information\",\"children\":[]},{\"level\":2,\"title\":\"3. How We Share, Transfer, and Publicly Disclose Your Personal Information\",\"slug\":\"_3-how-we-share-transfer-and-publicly-disclose-your-personal-information\",\"link\":\"#_3-how-we-share-transfer-and-publicly-disclose-your-personal-information\",\"children\":[]},{\"level\":2,\"title\":\"4. How We Use Cookies and Other Tracking Technologies\",\"slug\":\"_4-how-we-use-cookies-and-other-tracking-technologies\",\"link\":\"#_4-how-we-use-cookies-and-other-tracking-technologies\",\"children\":[]}],\"readingTime\":{\"minutes\":2.89,\"words\":868},\"filePathRelative\":\"privacy.md\",\"excerpt\":\"\\n<p>Welcome to our products. <strong>YishuLun Blog</strong> (including services provided by the website and other products, hereinafter referred to as \\\"products and services\\\") is developed and operated by <strong>LIYI</strong> (hereinafter referred to as \\\"we\\\"). Ensuring user data security and privacy protection is our primary task, this privacy policy clearly outlines the data collected and how it is processed when you visit and use our products and services.</p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
