import comp from "C:/Users/98301/work/yishulun_com_blog/src/.vuepress/.temp/pages/0000/00/00/如何使用Claude AI辅助创作小说.html.vue"
const data = JSON.parse("{\"path\":\"/0000/00/00/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8Claude%20AI%E8%BE%85%E5%8A%A9%E5%88%9B%E4%BD%9C%E5%B0%8F%E8%AF%B4.html\",\"title\":\"我如何使用 GPT4 与 Claude 辅助创作小说，及两个 AI 的辅助表现\",\"lang\":\"zh-CN\",\"frontmatter\":{\"gitInclude\":[],\"description\":\"我如何使用 GPT4 与 Claude 辅助创作小说，及两个 AI 的辅助表现 我研究了一下如何使用 Claude 辅助创作小说，总体感觉 Claude 的表现优于 GPT。GPT4 最大的缺点是急于完成指令，人类很难让它放缓节奏以增加渲染的厚度。Claude 辅助人类创建一个个片断，然后由人类自己组合，就像一张网，Claude 允许人类控制网上的节点...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://yishulun.com/0000/00/00/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8Claude%20AI%E8%BE%85%E5%8A%A9%E5%88%9B%E4%BD%9C%E5%B0%8F%E8%AF%B4.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"艺述论\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"我如何使用 GPT4 与 Claude 辅助创作小说，及两个 AI 的辅助表现\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"我如何使用 GPT4 与 Claude 辅助创作小说，及两个 AI 的辅助表现 我研究了一下如何使用 Claude 辅助创作小说，总体感觉 Claude 的表现优于 GPT。GPT4 最大的缺点是急于完成指令，人类很难让它放缓节奏以增加渲染的厚度。Claude 辅助人类创建一个个片断，然后由人类自己组合，就像一张网，Claude 允许人类控制网上的节点...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"我如何使用 GPT4 与 Claude 辅助创作小说，及两个 AI 的辅助表现\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"李艺\\\",\\\"url\\\":\\\"https://yishulun.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"1，故事创意\",\"slug\":\"_1-故事创意\",\"link\":\"#_1-故事创意\",\"children\":[]},{\"level\":2,\"title\":\"2，章节概要\",\"slug\":\"_2-章节概要\",\"link\":\"#_2-章节概要\",\"children\":[]},{\"level\":2,\"title\":\"3，章节大纲\",\"slug\":\"_3-章节大纲\",\"link\":\"#_3-章节大纲\",\"children\":[]},{\"level\":2,\"title\":\"4，创作小说\",\"slug\":\"_4-创作小说\",\"link\":\"#_4-创作小说\",\"children\":[{\"level\":3,\"title\":\"使用 GPT4 创作小说\",\"slug\":\"使用-gpt4-创作小说\",\"link\":\"#使用-gpt4-创作小说\",\"children\":[]},{\"level\":3,\"title\":\"使用 Claude 创作小说\",\"slug\":\"使用-claude-创作小说\",\"link\":\"#使用-claude-创作小说\",\"children\":[]}]},{\"level\":2,\"title\":\"5，编辑加工\",\"slug\":\"_5-编辑加工\",\"link\":\"#_5-编辑加工\",\"children\":[]},{\"level\":2,\"title\":\"小结\",\"slug\":\"小结\",\"link\":\"#小结\",\"children\":[]},{\"level\":2,\"title\":\"下一步\",\"slug\":\"下一步\",\"link\":\"#下一步\",\"children\":[]},{\"level\":2,\"title\":\"另一套故事创作提示模板\",\"slug\":\"另一套故事创作提示模板\",\"link\":\"#另一套故事创作提示模板\",\"children\":[]}],\"readingTime\":{\"minutes\":28.86,\"words\":8659},\"filePathRelative\":\"docs/novel/如何使用Claude AI辅助创作小说.md\",\"excerpt\":\"\\n<blockquote>\\n<p>我研究了一下如何使用 Claude 辅助创作小说，总体感觉 Claude 的表现优于 GPT。GPT4 最大的缺点是急于完成指令，人类很难让它放缓节奏以增加渲染的厚度。Claude 辅助人类创建一个个片断，然后由人类自己组合，就像一张网，Claude 允许人类控制网上的节点。进一步探索与使用 Claude 是有必要的。</p>\\n</blockquote>\\n<p>Claude 是 Anthropic 发布的人工智能工具，能够为我的小说创建提供很大帮助，许多作者发现 Claude 帮助作者创建的文本比 ChatGPT 更好。接下来我准备试用它们，对比研究一下它们的辅助创作表现。</p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
