import comp from "C:/Users/98301/work/yishulun_com_blog/src/.vuepress/.temp/pages/post/2024/01/18/2.html.vue"
const data = JSON.parse("{\"path\":\"/post/2024/01/18/2.html\",\"title\":\"体验世界单体最大北京城市图书馆，看到桌子的脑残设计，我不禁骂了一句：傻逼！\",\"lang\":\"zh-CN\",\"frontmatter\":{\"date\":\"2024-01-18T11:21:33.000Z\",\"tags\":[\"default\"],\"gitInclude\":[],\"description\":\"体验世界单体最大北京城市图书馆，看到桌子的脑残设计，我不禁骂了一句：傻逼！ 目录 位于通州区六环外的北京城市图书馆建成了，号称是吉尼斯单体面积第一的公共图书馆，7x24 小时对外开放。 铺天盖地的宣传push 单体第一与 7x24 小时开放，牛逼！看到这两个介绍，我就想去体验一下。体验之后，颇感失望。 失真的7x24 但其实不是真正的 7x24，只有一...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://yishulun.com/post/2024/01/18/2.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"艺述论\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"体验世界单体最大北京城市图书馆，看到桌子的脑残设计，我不禁骂了一句：傻逼！\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"体验世界单体最大北京城市图书馆，看到桌子的脑残设计，我不禁骂了一句：傻逼！ 目录 位于通州区六环外的北京城市图书馆建成了，号称是吉尼斯单体面积第一的公共图书馆，7x24 小时对外开放。 铺天盖地的宣传push 单体第一与 7x24 小时开放，牛逼！看到这两个介绍，我就想去体验一下。体验之后，颇感失望。 失真的7x24 但其实不是真正的 7x24，只有一...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"default\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-01-18T11:21:33.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"体验世界单体最大北京城市图书馆，看到桌子的脑残设计，我不禁骂了一句：傻逼！\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-01-18T11:21:33.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"李艺\\\",\\\"url\\\":\\\"https://yishulun.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"失真的7x24\",\"slug\":\"失真的7x24\",\"link\":\"#失真的7x24\",\"children\":[]},{\"level\":2,\"title\":\"人如果冷漠还不如用机器人\",\"slug\":\"人如果冷漠还不如用机器人\",\"link\":\"#人如果冷漠还不如用机器人\",\"children\":[]},{\"level\":2,\"title\":\"插座的脑残设计\",\"slug\":\"插座的脑残设计\",\"link\":\"#插座的脑残设计\",\"children\":[]},{\"level\":2,\"title\":\"让人憋屈的静音舱\",\"slug\":\"让人憋屈的静音舱\",\"link\":\"#让人憋屈的静音舱\",\"children\":[]},{\"level\":2,\"title\":\"怎么解决？\",\"slug\":\"怎么解决\",\"link\":\"#怎么解决\",\"children\":[]},{\"level\":2,\"title\":\"就餐\",\"slug\":\"就餐\",\"link\":\"#就餐\",\"children\":[]},{\"level\":2,\"title\":\"回顾\",\"slug\":\"回顾\",\"link\":\"#回顾\",\"children\":[]},{\"level\":2,\"title\":\"补充\",\"slug\":\"补充\",\"link\":\"#补充\",\"children\":[]}],\"readingTime\":{\"minutes\":11.35,\"words\":3406},\"filePathRelative\":\"posts/2024/2.md\",\"localizedDate\":\"2024年1月18日\",\"excerpt\":\"\\n<p>目录</p>\\n\\n<p>位于通州区六环外的北京城市图书馆建成了，号称是吉尼斯单体面积第一的公共图书馆，7x24 小时对外开放。</p>\\n<p>push</p>\\n<p>单体第一与 7x24 小时开放，牛逼！看到这两个介绍，我就想去体验一下。体验之后，颇感失望。</p>\\n<h2>失真的7x24</h2>\\n<p>但其实不是真正的 7x24，只有一层入门处潞云筑是全天侯的。周二至周日，上午 10 点开始，里面才正式开放。</p>\\n<figure><figcaption>Image</figcaption></figure>\\n<p>每天上午不到 10 点，内门门口的潞云筑就挤满了许多人。那些看到宣传来到这里体验的市民，不清楚状况，就一直在这里等。</p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
