import comp from "C:/Users/98301/work/yishulun_blog_mdandcode/src/.vuepress/.temp/pages/posts/2023/19.html.vue"
const data = JSON.parse("{\"path\":\"/posts/2023/19.html\",\"title\":\"我们如何使用 ChatGPT、Claude 和 Google Bard？\",\"lang\":\"zh-CN\",\"frontmatter\":{\"date\":\"2023-10-31T15:15:14.000Z\",\"tags\":[\"ChatGPT\"],\"gitInclude\":[],\"description\":\"image-20231031201628678image-20231031201628678 我们如何使用 ChatGPT、Claude 和 Google Bard？ 你好，今天聊一下如何使用 ChatGPT。 ChatGPT 很强大，且 ChatGPT 3.5 版本是公开与免费的，但并不是所有地方都可以使用它。有些地方甚至抵制使用。 2023 年 3...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://yishulun.com/posts/2023/19.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"艺述论\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"我们如何使用 ChatGPT、Claude 和 Google Bard？\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"image-20231031201628678image-20231031201628678 我们如何使用 ChatGPT、Claude 和 Google Bard？ 你好，今天聊一下如何使用 ChatGPT。 ChatGPT 很强大，且 ChatGPT 3.5 版本是公开与免费的，但并不是所有地方都可以使用它。有些地方甚至抵制使用。 2023 年 3...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"ChatGPT\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-10-31T15:15:14.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"我们如何使用 ChatGPT、Claude 和 Google Bard？\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-10-31T15:15:14.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"李艺\\\",\\\"url\\\":\\\"https://yishulun.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"如何注册 ChatGPT？\",\"slug\":\"如何注册-chatgpt\",\"link\":\"#如何注册-chatgpt\",\"children\":[]},{\"level\":2,\"title\":\"购买 GPT-4 月租服务\",\"slug\":\"购买-gpt-4-月租服务\",\"link\":\"#购买-gpt-4-月租服务\",\"children\":[]},{\"level\":2,\"title\":\"在 Bing 上使用 GPT-4\",\"slug\":\"在-bing-上使用-gpt-4\",\"link\":\"#在-bing-上使用-gpt-4\",\"children\":[]},{\"level\":2,\"title\":\"在 poe 上使用 ChatGPT\",\"slug\":\"在-poe-上使用-chatgpt\",\"link\":\"#在-poe-上使用-chatgpt\",\"children\":[]},{\"level\":2,\"title\":\"使用 Claude\",\"slug\":\"使用-claude\",\"link\":\"#使用-claude\",\"children\":[]},{\"level\":2,\"title\":\"使用 Google Bard\",\"slug\":\"使用-google-bard\",\"link\":\"#使用-google-bard\",\"children\":[]},{\"level\":2,\"title\":\"回顾\",\"slug\":\"回顾\",\"link\":\"#回顾\",\"children\":[]}],\"readingTime\":{\"minutes\":14.67,\"words\":4401},\"filePathRelative\":\"posts/2023/19.md\",\"localizedDate\":\"2023年10月31日\",\"excerpt\":\"<figure><figcaption>image-20231031201628678</figcaption></figure>\\n<h1>我们如何使用 ChatGPT、Claude 和 Google Bard？</h1>\\n<p>你好，今天聊一下如何使用 ChatGPT。</p>\\n<p>ChatGPT 很强大，且 ChatGPT 3.5 版本是公开与免费的，但并不是所有地方都可以使用它。有些地方甚至抵制使用。</p>\\n<p>2023 年 3 月 31 日，意大利个人数据保护局（Garante per la ProtezionedeiDatiPersonali）发表声明，宣布禁止意大利人使用 ChatGPT，同时限制 OpenAI 收集和处理意大利用户信息。意大利由此成为了第一个官方禁用 ChatGPT 的国家。</p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
