import comp from "C:/Users/98301/work/yishulun_blog_mdandcode/src/.vuepress/.temp/pages/posts/2023/42.html.vue"
const data = JSON.parse("{\"path\":\"/posts/2023/42.html\",\"title\":\"是被对手间谍策反，还是强大的 AI 操纵了人类意识，OpenAI 掌门 Sam Altman 被自己的公司扫地出门了\",\"lang\":\"zh-CN\",\"frontmatter\":{\"date\":\"2023-11-20T20:16:18.000Z\",\"tags\":[\"ChatGPT\"],\"gitInclude\":[],\"description\":\"微软聘请了 OpenAI 前首席执行官 Sam Altman微软聘请了 OpenAI 前首席执行官 Sam Altman 是被对手间谍策反，还是强大的 AI 操纵了人类意识，OpenAI 掌门 Sam Altman 被自己的公司扫地出门了 你好，今天聊一下 ChatGPT 的八卦。 对，不是聊它的技术，而是聊它的八卦——人事方面的八卦。具有相同鬼畜风格...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://yishulun.com/posts/2023/42.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"艺述论\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"是被对手间谍策反，还是强大的 AI 操纵了人类意识，OpenAI 掌门 Sam Altman 被自己的公司扫地出门了\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"微软聘请了 OpenAI 前首席执行官 Sam Altman微软聘请了 OpenAI 前首席执行官 Sam Altman 是被对手间谍策反，还是强大的 AI 操纵了人类意识，OpenAI 掌门 Sam Altman 被自己的公司扫地出门了 你好，今天聊一下 ChatGPT 的八卦。 对，不是聊它的技术，而是聊它的八卦——人事方面的八卦。具有相同鬼畜风格...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"ChatGPT\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-11-20T20:16:18.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"是被对手间谍策反，还是强大的 AI 操纵了人类意识，OpenAI 掌门 Sam Altman 被自己的公司扫地出门了\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-11-20T20:16:18.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"李艺\\\",\\\"url\\\":\\\"https://yishulun.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Altman 被自己的公司开除\",\"slug\":\"altman-被自己的公司开除\",\"link\":\"#altman-被自己的公司开除\",\"children\":[]},{\"level\":2,\"title\":\"微软最成功的投资之一\",\"slug\":\"微软最成功的投资之一\",\"link\":\"#微软最成功的投资之一\",\"children\":[]},{\"level\":2,\"title\":\"整件事情的发展经过，皆因理念之争\",\"slug\":\"整件事情的发展经过-皆因理念之争\",\"link\":\"#整件事情的发展经过-皆因理念之争\",\"children\":[]},{\"level\":2,\"title\":\"理念之争由来已久\",\"slug\":\"理念之争由来已久\",\"link\":\"#理念之争由来已久\",\"children\":[]},{\"level\":2,\"title\":\"OpenAI 成立的初衷\",\"slug\":\"openai-成立的初衷\",\"link\":\"#openai-成立的初衷\",\"children\":[]},{\"level\":2,\"title\":\"回顾\",\"slug\":\"回顾\",\"link\":\"#回顾\",\"children\":[]}],\"readingTime\":{\"minutes\":12.76,\"words\":3828},\"filePathRelative\":\"posts/2023/42.md\",\"localizedDate\":\"2023年11月21日\",\"excerpt\":\"<figure><figcaption>微软聘请了 OpenAI 前首席执行官 Sam Altman</figcaption></figure>\\n<h1>是被对手间谍策反，还是强大的 AI 操纵了人类意识，OpenAI 掌门 Sam Altman 被自己的公司扫地出门了</h1>\\n<p>你好，今天聊一下 ChatGPT 的八卦。</p>\\n<p>对，不是聊它的技术，而是聊它的八卦——人事方面的八卦。具有相同鬼畜风格的事情，在 1985 年 4 月也发生过一次，那一次乔布斯被自己亲手创建的苹果公司赶出去了。不过，当时人们并没有意识到苹果公司开除乔布斯是多么荒谬；这一次，人们似乎对 OpenAI 重事会开除 Sam Altman 表现出了同等的惋惜和惊讶。</p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
