import comp from "C:/Users/98301/work/yishulun_com_blog/src/.vuepress/.temp/pages/post/2023/11/05/23.html.vue"
const data = JSON.parse("{\"path\":\"/post/2023/11/05/23.html\",\"title\":\"马斯克发布全新 AI——Grok，宣称世界第三，现在加入列表等待舱门开启\",\"lang\":\"zh-CN\",\"frontmatter\":{\"date\":\"2023-11-05T15:00:17.000Z\",\"tags\":[\"Grok\"],\"gitInclude\":[],\"description\":\"grokgrok 马斯克发布全新 AI——Grok，宣称世界第三，现在加入列表等待舱门开启 下文中的“我们”，指代 Grok 的开发团队。这是一篇译稿，引用部分为探长添加。 Grok 是一款模仿《银河系漫游指南》的人工智能，因此几乎可以回答任何问题，更难的是，它甚至可以建议要问什么问题！ 注：《银河系漫游指南》是一部由英国作家道格拉斯·亚当斯创作的系列...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://yishulun.com/post/2023/11/05/23.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"艺述论\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"马斯克发布全新 AI——Grok，宣称世界第三，现在加入列表等待舱门开启\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"grokgrok 马斯克发布全新 AI——Grok，宣称世界第三，现在加入列表等待舱门开启 下文中的“我们”，指代 Grok 的开发团队。这是一篇译稿，引用部分为探长添加。 Grok 是一款模仿《银河系漫游指南》的人工智能，因此几乎可以回答任何问题，更难的是，它甚至可以建议要问什么问题！ 注：《银河系漫游指南》是一部由英国作家道格拉斯·亚当斯创作的系列...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Grok\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-11-05T15:00:17.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"马斯克发布全新 AI——Grok，宣称世界第三，现在加入列表等待舱门开启\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-11-05T15:00:17.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"李艺\\\",\\\"url\\\":\\\"https://yishulun.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"我们为何构建 Grok\",\"slug\":\"我们为何构建-grok\",\"link\":\"#我们为何构建-grok\",\"children\":[]},{\"level\":2,\"title\":\"前往 Grok-1 的旅程\",\"slug\":\"前往-grok-1-的旅程\",\"link\":\"#前往-grok-1-的旅程\",\"children\":[]},{\"level\":2,\"title\":\"xAI 的工程\",\"slug\":\"xai-的工程\",\"link\":\"#xai-的工程\",\"children\":[]},{\"level\":2,\"title\":\"xAI 的研究\",\"slug\":\"xai-的研究\",\"link\":\"#xai-的研究\",\"children\":[]},{\"level\":2,\"title\":\"抢先体验 Grok\",\"slug\":\"抢先体验-grok\",\"link\":\"#抢先体验-grok\",\"children\":[]},{\"level\":2,\"title\":\"回顾\",\"slug\":\"回顾\",\"link\":\"#回顾\",\"children\":[]}],\"readingTime\":{\"minutes\":12.19,\"words\":3658},\"filePathRelative\":\"posts/2023/23.md\",\"localizedDate\":\"2023年11月5日\",\"excerpt\":\"<figure><figcaption>grok</figcaption></figure>\\n<h1>马斯克发布全新 AI——Grok，宣称世界第三，现在加入列表等待舱门开启</h1>\\n<blockquote>\\n<p>下文中的“我们”，指代 Grok 的开发团队。这是一篇译稿，引用部分为探长添加。</p>\\n</blockquote>\\n<p>Grok 是一款模仿《银河系漫游指南》的人工智能，<strong>因此几乎可以回答任何问题，更难的是，它甚至可以建议要问什么问题！</strong></p>\\n<blockquote>\\n<p>注：《银河系漫游指南》是一部由英国作家道格拉斯·亚当斯创作的系列科幻喜剧小说。《银河系漫游指南》讲述了地球人阿瑟·丹特和他的朋友福特·派法特的故事。福特是一名来自参宿四的宇宙旅行者，他一直在地球上伪装成人类。在地球被沃贡人摧毁后，阿瑟和福特搭上了黄金之心号太空船，开始了穿越银河系的冒险。</p>\\n</blockquote>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
