import comp from "C:/Users/98301/work/yishulun_com_blog/src/.vuepress/.temp/pages/post/2002/12/22/about.html.vue"
const data = JSON.parse("{\"path\":\"/post/2002/12/22/about.html\",\"title\":\"关于作者\",\"lang\":\"zh-CN\",\"frontmatter\":{\"editLink\":false,\"comment\":false,\"pageInfo\":false,\"date\":\"2002-12-22T10:50:22.000Z\",\"footer\":false,\"sidebar\":false,\"aside\":false,\"hideComment\":true,\"hideShare\":true,\"gitInclude\":[],\"description\":\"关于作者 艺术论的哲学应用研究，主要专注于在计算机编程、网文创作、书法篆刻等领域的应探索。 我一位老码农，有超过 20 年的互联网软件研发经验，曾深度参与研发并在腾讯 QQ 上线音视频直播产品，服务用户量高达数千万，是国内早期闪客之一，曾制定课件标准并完成全平台课件产品研发，获 Adobe 官方认可，成为中国区 15 位社区管理员之一。在北京协同创新研...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://yishulun.com/post/2002/12/22/about.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"艺述论\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"关于作者\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"关于作者 艺术论的哲学应用研究，主要专注于在计算机编程、网文创作、书法篆刻等领域的应探索。 我一位老码农，有超过 20 年的互联网软件研发经验，曾深度参与研发并在腾讯 QQ 上线音视频直播产品，服务用户量高达数千万，是国内早期闪客之一，曾制定课件标准并完成全平台课件产品研发，获 Adobe 官方认可，成为中国区 15 位社区管理员之一。在北京协同创新研...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2002-12-22T10:50:22.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"关于作者\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2002-12-22T10:50:22.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"李艺\\\",\\\"url\\\":\\\"https://yishulun.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"联系方式\",\"slug\":\"联系方式\",\"link\":\"#联系方式\",\"children\":[]},{\"level\":2,\"title\":\"个人简历\",\"slug\":\"个人简历\",\"link\":\"#个人简历\",\"children\":[{\"level\":3,\"title\":\"传统出版物\",\"slug\":\"传统出版物\",\"link\":\"#传统出版物\",\"children\":[]},{\"level\":3,\"title\":\"电子出版物\",\"slug\":\"电子出版物\",\"link\":\"#电子出版物\",\"children\":[]},{\"level\":3,\"title\":\"奖项与荣誉\",\"slug\":\"奖项与荣誉\",\"link\":\"#奖项与荣誉\",\"children\":[]},{\"level\":3,\"title\":\"公益活动\",\"slug\":\"公益活动\",\"link\":\"#公益活动\",\"children\":[]}]},{\"level\":2,\"title\":\"赞赏支持\",\"slug\":\"赞赏支持\",\"link\":\"#赞赏支持\",\"children\":[]}],\"readingTime\":{\"minutes\":3.64,\"words\":1092},\"filePathRelative\":\"about.md\",\"localizedDate\":\"2002年12月22日\",\"excerpt\":\"\\n<!-- <script setup>\\nimport { VPTeamMembers } from 'vitepress/theme'\\n\\nconst members = [\\n  {\\n    avatar: 'https://yishulun.com/avatar.png',\\n    name: 'LIYI',\\n    title: '艺术论哲学应用研究',\\n    links: [\\n      { icon: 'github', link: 'https://github.com/rixingyike' },\\n      { icon: 'twitter', link: 'https://twitter.com/coderliyi' }\\n    ]\\n  },\\n]\\n</script>\\n\\n<VPTeamMembers size=\\\"small\\\" :members=\\\"members\\\" /> -->\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
