import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.cc2b3d55.js";
const __pageData = JSON.parse('{"title":"小程序从0到1：豆瓣接口替代网址可以在线访问了","description":"","frontmatter":{"sidebar":false,"date":"2020-01-01T00:00:00.000Z"},"headers":[],"relativePath":"posts/2020/01.md","filePath":"posts/2020/01.md"}');
const _sfc_main = { name: "posts/2020/01.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="小程序从0到1-豆瓣接口替代网址可以在线访问了" tabindex="-1">小程序从0到1：豆瓣接口替代网址可以在线访问了 <a class="header-anchor" href="#小程序从0到1-豆瓣接口替代网址可以在线访问了" aria-label="Permalink to &quot;小程序从0到1：豆瓣接口替代网址可以在线访问了&quot;">​</a></h1><p>《小程序从0到1》这本书即将再版印刷了，趁此机会，作者必将豆瓣服务器地址从示例中拿去，原因大家都清楚。前几日，为了方便读者朋友在本地学习与测试，作者用 Go 语言写了一个替代小工具，如下文章所述：</p><p><a href="http://mp.weixin.qq.com/s/-6UYVXvTwxlz5poybBFHUg" target="_blank" rel="noreferrer">还一个技术债：豆瓣接口代替小工具</a></p><p>现在，这个小工具也不需要了。为了进一步方便读者，作者已经将该程序部署在了作者的服务器上。购买服务器可是花了不少银子。</p><p>使用方法：</p><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki github-dark vp-code-dark"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">将小程序源码中的</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">https://api.douban.com/v2</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">替换为</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">https://api.rixingyike.com/doubanapiv2</span></span></code></pre><pre class="shiki github-light vp-code-light"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1" })}">将小程序源码中的</span><span style="${ssrRenderStyle({ "color": "#24292E" })}"> </span><span style="${ssrRenderStyle({ "color": "#032F62" })}">https://api.douban.com/v2</span><span style="${ssrRenderStyle({ "color": "#24292E" })}"> </span><span style="${ssrRenderStyle({ "color": "#032F62" })}">替换为</span><span style="${ssrRenderStyle({ "color": "#24292E" })}"> </span><span style="${ssrRenderStyle({ "color": "#032F62" })}">https://api.rixingyike.com/doubanapiv2</span></span></code></pre></div><p>具体的新旧接口对应关系为：</p><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki github-dark vp-code-dark"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">//</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">https://api.douban.com/v2/movie/coming_soon?start=</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">0</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&amp;count</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">3</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">//</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">https://api.rixingyike.com/doubanapiv2/movie/coming_soon?start=</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">0</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&amp;count</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">3</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">//</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">https://api.douban.com/v2/movie/search?q=</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">\${this.data.searchWords}&amp;start</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">\${start}&amp;count</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">\${this.data.size}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">//</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">https://api.rixingyike.com/doubanapiv2/movie/search?q=和平</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&amp;start</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">0</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&amp;count</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">10</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">//</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">https://api.douban.com/v2/movie/</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">\${this.data.type}</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">?start=</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">\${start}&amp;count</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> \${this.data.size}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">//</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">https://api.rixingyike.com/doubanapiv2/movie/in_theaters?start=</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">0</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&amp;count</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">10</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">//</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">https://api.douban.com/v2/movie/subject/</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">\${options.id}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">//</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">https://api.rixingyike.com/doubanapiv2/movie/subject/3267549</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">//</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">https://api.douban.com/v2/movie/bang/</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">\${board.key}</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">?start=</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">0</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&amp;count</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">10</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">//</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">https://api.rixingyike.com/doubanapiv2/movie/top250?start=</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">0</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&amp;count</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">10</span></span></code></pre><pre class="shiki github-light vp-code-light"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1" })}">//</span><span style="${ssrRenderStyle({ "color": "#24292E" })}"> </span><span style="${ssrRenderStyle({ "color": "#032F62" })}">https://api.douban.com/v2/movie/coming_soon?start=</span><span style="${ssrRenderStyle({ "color": "#005CC5" })}">0</span><span style="${ssrRenderStyle({ "color": "#24292E" })}">&amp;count</span><span style="${ssrRenderStyle({ "color": "#D73A49" })}">=</span><span style="${ssrRenderStyle({ "color": "#005CC5" })}">3</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1" })}">//</span><span style="${ssrRenderStyle({ "color": "#24292E" })}"> </span><span style="${ssrRenderStyle({ "color": "#032F62" })}">https://api.rixingyike.com/doubanapiv2/movie/coming_soon?start=</span><span style="${ssrRenderStyle({ "color": "#005CC5" })}">0</span><span style="${ssrRenderStyle({ "color": "#24292E" })}">&amp;count</span><span style="${ssrRenderStyle({ "color": "#D73A49" })}">=</span><span style="${ssrRenderStyle({ "color": "#005CC5" })}">3</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1" })}">//</span><span style="${ssrRenderStyle({ "color": "#24292E" })}"> </span><span style="${ssrRenderStyle({ "color": "#032F62" })}">https://api.douban.com/v2/movie/search?q=</span><span style="${ssrRenderStyle({ "color": "#24292E" })}">\${this.data.searchWords}&amp;start</span><span style="${ssrRenderStyle({ "color": "#D73A49" })}">=</span><span style="${ssrRenderStyle({ "color": "#24292E" })}">\${start}&amp;count</span><span style="${ssrRenderStyle({ "color": "#D73A49" })}">=</span><span style="${ssrRenderStyle({ "color": "#24292E" })}">\${this.data.size}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1" })}">//</span><span style="${ssrRenderStyle({ "color": "#24292E" })}"> </span><span style="${ssrRenderStyle({ "color": "#032F62" })}">https://api.rixingyike.com/doubanapiv2/movie/search?q=和平</span><span style="${ssrRenderStyle({ "color": "#24292E" })}">&amp;start</span><span style="${ssrRenderStyle({ "color": "#D73A49" })}">=</span><span style="${ssrRenderStyle({ "color": "#005CC5" })}">0</span><span style="${ssrRenderStyle({ "color": "#24292E" })}">&amp;count</span><span style="${ssrRenderStyle({ "color": "#D73A49" })}">=</span><span style="${ssrRenderStyle({ "color": "#005CC5" })}">10</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1" })}">//</span><span style="${ssrRenderStyle({ "color": "#24292E" })}"> </span><span style="${ssrRenderStyle({ "color": "#032F62" })}">https://api.douban.com/v2/movie/</span><span style="${ssrRenderStyle({ "color": "#24292E" })}">\${this.data.type}</span><span style="${ssrRenderStyle({ "color": "#032F62" })}">?start=</span><span style="${ssrRenderStyle({ "color": "#24292E" })}">\${start}&amp;count</span><span style="${ssrRenderStyle({ "color": "#D73A49" })}">=</span><span style="${ssrRenderStyle({ "color": "#24292E" })}"> \${this.data.size}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1" })}">//</span><span style="${ssrRenderStyle({ "color": "#24292E" })}"> </span><span style="${ssrRenderStyle({ "color": "#032F62" })}">https://api.rixingyike.com/doubanapiv2/movie/in_theaters?start=</span><span style="${ssrRenderStyle({ "color": "#005CC5" })}">0</span><span style="${ssrRenderStyle({ "color": "#24292E" })}">&amp;count</span><span style="${ssrRenderStyle({ "color": "#D73A49" })}">=</span><span style="${ssrRenderStyle({ "color": "#005CC5" })}">10</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1" })}">//</span><span style="${ssrRenderStyle({ "color": "#24292E" })}"> </span><span style="${ssrRenderStyle({ "color": "#032F62" })}">https://api.douban.com/v2/movie/subject/</span><span style="${ssrRenderStyle({ "color": "#24292E" })}">\${options.id}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1" })}">//</span><span style="${ssrRenderStyle({ "color": "#24292E" })}"> </span><span style="${ssrRenderStyle({ "color": "#032F62" })}">https://api.rixingyike.com/doubanapiv2/movie/subject/3267549</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1" })}">//</span><span style="${ssrRenderStyle({ "color": "#24292E" })}"> </span><span style="${ssrRenderStyle({ "color": "#032F62" })}">https://api.douban.com/v2/movie/bang/</span><span style="${ssrRenderStyle({ "color": "#24292E" })}">\${board.key}</span><span style="${ssrRenderStyle({ "color": "#032F62" })}">?start=</span><span style="${ssrRenderStyle({ "color": "#005CC5" })}">0</span><span style="${ssrRenderStyle({ "color": "#24292E" })}">&amp;count</span><span style="${ssrRenderStyle({ "color": "#D73A49" })}">=</span><span style="${ssrRenderStyle({ "color": "#005CC5" })}">10</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6F42C1" })}">//</span><span style="${ssrRenderStyle({ "color": "#24292E" })}"> </span><span style="${ssrRenderStyle({ "color": "#032F62" })}">https://api.rixingyike.com/doubanapiv2/movie/top250?start=</span><span style="${ssrRenderStyle({ "color": "#005CC5" })}">0</span><span style="${ssrRenderStyle({ "color": "#24292E" })}">&amp;count</span><span style="${ssrRenderStyle({ "color": "#D73A49" })}">=</span><span style="${ssrRenderStyle({ "color": "#005CC5" })}">10</span></span></code></pre></div><p>2020年1月1日</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("posts/2020/01.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const _01 = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  _01 as default
};
