import comp from "C:/Users/98301/work/yishulun_com_blog/src/.vuepress/.temp/pages/post/2023/10/29/17.html.vue"
const data = JSON.parse("{\"path\":\"/post/2023/10/29/17.html\",\"title\":\"篆刻刻刀如何选择？不要选择哪些刻刀？\",\"lang\":\"zh-CN\",\"frontmatter\":{\"date\":\"2023-10-29T17:17:27.000Z\",\"tags\":[\"篆刻\"],\"gitInclude\":[],\"description\":\"篆刻刻刀如何选择？不要选择哪些刻刀？ 篆刻刻刀都是平刃刀，没有选择尖角或斜角的，因为篆刻是用 90 度的刀角刻印的，并不是用刀尖刻印的。 在了解如何选择刻刀之前，我们需要先细致看一下篆刻的分类。明确了以下这些分类，及不同分类的优缺点，才能彻底明白如何选择。 依平刃宽度划分类别 刻刀从平刃的宽度分，常用的有 10mm、8mm、6mm、4mm，一般都是偶数...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://yishulun.com/post/2023/10/29/17.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"艺述论\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"篆刻刻刀如何选择？不要选择哪些刻刀？\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"篆刻刻刀如何选择？不要选择哪些刻刀？ 篆刻刻刀都是平刃刀，没有选择尖角或斜角的，因为篆刻是用 90 度的刀角刻印的，并不是用刀尖刻印的。 在了解如何选择刻刀之前，我们需要先细致看一下篆刻的分类。明确了以下这些分类，及不同分类的优缺点，才能彻底明白如何选择。 依平刃宽度划分类别 刻刀从平刃的宽度分，常用的有 10mm、8mm、6mm、4mm，一般都是偶数...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"篆刻\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-10-29T17:17:27.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"篆刻刻刀如何选择？不要选择哪些刻刀？\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-10-29T17:17:27.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"李艺\\\",\\\"url\\\":\\\"https://yishulun.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"依平刃宽度划分类别\",\"slug\":\"依平刃宽度划分类别\",\"link\":\"#依平刃宽度划分类别\",\"children\":[]},{\"level\":2,\"title\":\"以刀刃材质划分类别\",\"slug\":\"以刀刃材质划分类别\",\"link\":\"#以刀刃材质划分类别\",\"children\":[]},{\"level\":2,\"title\":\"以开刃角度划分类别\",\"slug\":\"以开刃角度划分类别\",\"link\":\"#以开刃角度划分类别\",\"children\":[]},{\"level\":2,\"title\":\"吴昌硕与齐白石的刻刀\",\"slug\":\"吴昌硕与齐白石的刻刀\",\"link\":\"#吴昌硕与齐白石的刻刀\",\"children\":[]},{\"level\":2,\"title\":\"我们如何选择刻刀？\",\"slug\":\"我们如何选择刻刀\",\"link\":\"#我们如何选择刻刀\",\"children\":[]},{\"level\":2,\"title\":\"不要选择什么样的刻刀？\",\"slug\":\"不要选择什么样的刻刀\",\"link\":\"#不要选择什么样的刻刀\",\"children\":[]},{\"level\":2,\"title\":\"如何自己磨制刻刀？\",\"slug\":\"如何自己磨制刻刀\",\"link\":\"#如何自己磨制刻刀\",\"children\":[]},{\"level\":2,\"title\":\"回顾\",\"slug\":\"回顾\",\"link\":\"#回顾\",\"children\":[]},{\"level\":2,\"title\":\"10/30补充，章料的选择\",\"slug\":\"_10-30补充-章料的选择\",\"link\":\"#_10-30补充-章料的选择\",\"children\":[]}],\"readingTime\":{\"minutes\":15.39,\"words\":4618},\"filePathRelative\":\"posts/2023/17.md\",\"localizedDate\":\"2023年10月30日\",\"excerpt\":\"\\n<p>篆刻刻刀都是平刃刀，没有选择尖角或斜角的，因为篆刻是用 90 度的刀角刻印的，并不是用刀尖刻印的。</p>\\n<p>在了解如何选择刻刀之前，我们需要先细致看一下篆刻的分类。明确了以下这些分类，及不同分类的优缺点，才能彻底明白如何选择。</p>\\n<h2>依平刃宽度划分类别</h2>\\n<p>刻刀从平刃的宽度分，常用的有 10mm、8mm、6mm、4mm，一般都是偶数毫米长度，也有奇数的，但奇数刃宽的刻刀很少见。更大的有 12mm，更小的还有 3mm，再小的就没有了。</p>\\n<p>章料的印面大小一般有 3cm、2.5cm、2cm，一般都是使用 1/2 印面尺寸或更小的刻刀进行刻制。小刻刀可以刻制大印面，但大刻刀刻小印面总是捉刀见肘的。</p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
