name: Deploy (部署文档)

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # 检出代码
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 设置 Node.js
      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 安装 yarn
      - name: 安装 yarn
        run: npm install -g yarn

      # 安装依赖
      - name: 安装依赖
        run: yarn install

      # 构建 VuePress 文档
      - name: Build (构建文档)
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: yarn docs:build

      # 上传构建结果到 GitHub Pages
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          path: src/.vuepress/dist

      # 部署到外部仓库
      - name: Deploy to external repository
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.EXTERNAL_REPOSITORY_PERSONAL_ACCESS_TOKEN }}
        with:
          source-directory: src/.vuepress/dist/
          destination-github-username: rixingyike
          destination-repository-name: yishulun.com
          user-email: 9830131@qq.com
          target-branch: "main"

      # 测试获取由 push-to-another-repository 导出的变量
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
